server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/kali786516/pluralsight-spring-cloudconfig-wa-tolls # default
          #username: abc
          #password: abc
          search-paths:
            - 'station*'
          repos:
            local:
              pattern: '*/local'
              uri: https://github.com/kali786516/pluralsight-spring-cloudconfig-wa-tolls # alt
              search-paths:
                - 'station*'
security:
  basic:
    enabled: true
  user:
    name: kali.tummala@gmail.com
    password: Sairam786516